feat: add contexts on datastore methods
ipfs/go-filestore pull request #55
Opened 2021-11-10 22:23 UTC by guseggert

2021-11-10 22:35 UTC, petar approved these changes

2021-11-10 22:35 UTC, petar commented on util.go
>  	}
Either the lambda returned below or ListAll() should take a context. Probably ok to leave it like this for now.

2021-11-10 22:54 UTC, guseggert commented
This is wrong b/c I didn't realize that go-ipfs consumes go-filestore@v0.0.3 whereas this is building on the breaking changes introduced in v1.0.0, so I need to backport this.

2021-11-19 17:37 UTC, aschmahmann commented
We still need to have a v1 version of this for use in places like lotus

2021-11-19 17:57 UTC, aschmahmann requested changes
This isn't quite ready, it should match #55

2021-11-22 18:01 UTC, marten-seemann commented
This should be a v2, as the API was changed.

2021-11-22 19:58 UTC, aschmahmann commented
@marten-seemann we're not bumping these to v2 as right now there is a good deal of complexity around the v0 and v1 (both in use) of this repo and they need to be swappable (i.e. I need to be able to drop in v1 as a v0 replacement).

This choice is independent of, but related to, the decision to not release go-datastore as a v2 despite the breaking change with contexts. So we're knowingly doing the wrong thing.

2021-11-22 20:18 UTC, aschmahmann approved these changes

2021-11-22 20:19 UTC, merged